Controllers/CidadeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PizzaDelivery.Extensions;
using PizzaDelivery.Interfaces;
using PizzaDelivery.Models;
using PizzaDelivery.ViewModels;
using static PizzaDelivery.Helper;

namespace PizzaDelivery.Controllers
{
    public class CidadeController : Controller
    {
        private readonly IEstadoRepository _estadoRepository;
        private readonly ICidadeRepository _cidadeRepository;
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public CidadeController(IEstadoRepository estadoRepository, ICidadeRepository cidadeRepository, IUnitOfWork uow, IMapper mapper)
        {
            _estadoRepository = estadoRepository;
            _cidadeRepository = cidadeRepository;
            _mapper = mapper;
            _uow = uow;
        }

        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> Index()
        {
            ViewBag.Estados = await _estadoRepository.GetOptionsAsync("[TODOS]");
            return View(await _cidadeRepository.GetViewAllList().ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> GetData([FromForm] string id)
        {
            var retorno = await _cidadeRepository.GetViewAllList(id).ToListAsync();

            return Json(new { isValid = true, html = await RenderRazorViewToStringAsync(this, "_ViewAll", retorno) });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<JsonResult> GetOptions(string id)
        {
            var retorno = await _cidadeRepository.GetOptions(c => c.EstadoId == id);

            return Json(retorno);
        }

        // GET: Cidade/AddOrEdit   (Insert)
        // GET: Cidade/AddOrEdit/5 (Update)
        [HttpGet]
        [NoDirectAccess]
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> AddOrEdit(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var cidadeDB = await _cidadeRepository.GetByIdAsync(id);
                if (cidadeDB == null)
                {
                    this.MostrarMensagem("Ops, não encontrei a cidade.", true);
                    return RedirectToAction("Index");
                }
                var cidadeVM = _mapper.Map<CidadeAddOrEditViewModel>(cidadeDB);

                cidadeVM.Estados = await _estadoRepository.GetOptionsAsync("Selecione...");

                return View(cidadeVM);
            }
            return View(new CidadeAddOrEditViewModel() { Estados = await _estadoRepository.GetOptionsAsync("Selecione...") });
        }

        // POST: Cidade/AddOrEdit   (Create)
        // POST: Cidade/AddOrEdit/5 (Edit)
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> AddOrEdit([FromForm] CidadeAddOrEditViewModel cidadeVM)
        {
            if (ModelState.IsValid)
            {
                //Alteração
                if (!string.IsNullOrEmpty(cidadeVM.Id))
                {
                    var cidadeDB = await _cidadeRepository.GetByIdAsync(cidadeVM.Id);
                    if (cidadeDB != null)
                    {
                        _mapper.Map(cidadeVM, cidadeDB);

                        try
                        {
                            _cidadeRepository.Update(cidadeDB);

                            if ((await _uow.CommitAsync()) > 0)
                            {
                                this.MostrarMensagem($"Pronto, alterei a cidade {cidadeDB.Cidade}.");
                            }
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            _uow.RollBack();
                            if (!_cidadeRepository.EntidadeExiste(cidadeDB.Id))
                            {
                                this.MostrarMensagem($"Ops, não encontrei a cidade {cidadeDB.Cidade}.", true);
                            }
                            else
                            {
                                this.MostrarMensagem($"Ops, não consegui alterar a cidade {cidadeDB.Cidade}.", true);
                                throw;
                            }
                        };
                    }
                    else
                    {
                        this.MostrarMensagem($"Ops, não encontrei a cidade {cidadeVM.Cidade}.", true);
                    }
                }
                else
                {
                    //Inclusão
                    //cidadeVM.Id = Guid.NewGuid().ToString();
                    var cidadeDB = _mapper.Map<CidadeModel>(cidadeVM);

                    try
                    {
                        await _cidadeRepository.AddAsync(cidadeDB);

                        if ((await _uow.CommitAsync()) > 0)
                        {
                            this.MostrarMensagem($"Pronto, salvei a cidade {cidadeDB.Cidade}.");
                        }
                    }
                    catch (Exception)
                    {
                        _uow.RollBack();
                        this.MostrarMensagem($"Ops, não consegui salvar a cidade {cidadeDB.Cidade}.", true);
                        throw;
                    };
                }
                return Json(new { isValid = true, html = await RenderRazorViewToStringAsync(this, "_ViewAll", await _cidadeRepository.GetViewAllList().ToListAsync()) });
            }
            return Json(new { isValid = false, html = await RenderRazorViewToStringAsync(this, "AddOrEdit", cidadeVM) });
        }

        // GET: Cidade/Delete/5
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> Delete(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var cidadeDB = await _cidadeRepository.GetByIdAsync(id);
                if (cidadeDB != null)
                {
                    return View(_mapper.Map<CidadeAddOrEditViewModel>(cidadeDB));
                }
                else
                {
                    this.MostrarMensagem("Ops, não encontrei a cidade.", true);
                }
            }
            else
            {
                this.MostrarMensagem("Nenhuma cidade foi informada.", true);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: Cidade/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var cidadeDB = await _cidadeRepository.GetByIdAsync(id);
                if (cidadeDB != null)
                {
                    try
                    {
                        _cidadeRepository.Remove(cidadeDB);

                        if ((await _uow.CommitAsync()) > 0)
                            this.MostrarMensagem($"Pronto, excluí a cidade {cidadeDB.Cidade}.");
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!_cidadeRepository.EntidadeExiste(cidadeDB.Id))
                        {
                            this.MostrarMensagem($"Ops, não encontrei a cidade {cidadeDB.Cidade}.", true);
                        }
                        else
                        {
                            this.MostrarMensagem($"Ops, não consegui excluir a cidade {cidadeDB.Cidade}.", true);
                            throw;
                        }
                    };
                }
                else
                {
                    this.MostrarMensagem("Ops, não encontrei a cidade", true);
                }
            }
            else
            {
                this.MostrarMensagem("Nenhuma cidade foi informada.", true);
            }
            return Json(new { isValid = true, html = await RenderRazorViewToStringAsync(this, "_ViewAll", await _cidadeRepository.GetViewAllList().ToListAsync()) });
        }

        //GET: Cidade/Details/5
        [HttpGet]
        [Authorize(Roles = "administrador")]
        public async Task<IActionResult> Details(string id)
        {
            if (!string.IsNullOrEmpty(id))
            {
                var cidadeDB = await _cidadeRepository.GetByIdAsync(id);
                if (cidadeDB != null)
                {
                    var cidadeVM = _mapper.Map<CidadeAddOrEditViewModel>(cidadeDB);
                    return View(cidadeVM);
                }
                else
                {
                    this.MostrarMensagem("Ops! Não encontrei a cidade.", true);
                }
            }
            else
            {
                this.MostrarMensagem("Nenhuma cidade foi informada.", true);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_ConsultaCEP.cshtml
@* https://viacep.com.br/exemplo/jquery/ *@
<script type="text/javascript">

    $(document).ready(() => {

        function limpar_dados_cep() {
            //Limpa valores do formulário de cep.
            $("#Logradouro").val('');
            $("#Bairro").val('');
            $("#Cidade").val('');
            $("#Estado").val('');
            $("#endereco").text('Digite um CEP válido e aguarde.');

            //Mostra o ícone de inválido
            $("#cep_none").removeClass("d-none");
            $("#cep_loading").addClass("d-none");
            $("#cep_checked").addClass("d-none");
        }

        function consultar_cep() {
            console.log($("#CEP").val());
            //Nova variável "cep" somente com dígitos.
            var cep = $("#CEP").val()?.replace(/\D/g, '');
            //Verifica se campo cep possui valor informado.
            if (cep != "") {
                //Expressão regular para validar o CEP.
                var validacep = /^[0-9]{8}$/;
                //Valida o formato do CEP.
                if (validacep.test(cep)) {
                    //Mostra o ícone de carregamento
                    $("#cep_none").addClass("d-none");
                    $("#cep_loading").removeClass("d-none");
                    $("#cep_checked").addClass("d-none");
                    //Consulta o webservice viacep.com.br/
                    $.getJSON("//viacep.com.br/ws/" + cep + "/json/", function (result) {
                        //Mostra o ícone de verificado
                        $("#cep_none").addClass("d-none");
                        $("#cep_loading").addClass("d-none");
                        $("#cep_checked").removeClass("d-none");
                        if (!("erro" in result)) {
                            //Atualiza os campos com os valores da consulta.
                            $("#Logradouro").val(result.logradouro);
                            $("#Bairro").val(result.bairro);
                            $("#Cidade").val(result.localidade);
                            $("#Estado").val(result.uf);
                            $("#endereco").text(result.logradouro + ", " +
                                result.bairro + ", " + result.localidade + ", " + result.uf + ".").removeClass('text-danger').addClass('text-muted');
                        } //end if.
                        else {
                            //cep pesquisado não foi encontrado.
                            limpar_dados_cep();
                            $("#endereco").text("Este CEP não foi encontrado.").addClass('text-danger').removeClass('text-muted');
                        }
                    });
                } //end if.
                else {
                    //cep é inválido.
                    limpar_dados_cep();
                    $("#endereco").text("Este CEP não é válido.").addClass('text-danger').removeClass('text-muted');
                }
            } //end if.
            else {
                //cep sem valor, limpa formulário.
                limpar_dados_cep();
                $("#endereco").text("Digite um CEP válido e aguarde.").removeClass('text-danger').addClass('text-muted');
            }
        }

        //Quando o campo cep perde o foco.
        $("#CEP").blur(consultar_cep);
        consultar_cep();
    });
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RappiPizzas - @ViewBag.Subtitulo</title>
    <link rel="shortcut icon" href="~/img/assets/iconerapipizzas.ico" type="image/x-icon">
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

    @await RenderSectionAsync("styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg fixed-top shadow-sm border-bottom bg-gradient">
        <div class="container-fluid">
            <a class="navbar-brand me-4" href="/"><img src="\img\assets\logo02hor.png" alt="RappiPizzas" width="220" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mb-2 mb-lg-0 text-center me-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index" asp-link-class="link-ativo">Cardápio</a>
                    </li>
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        @if (Context.User.IsInRole("administrador") || Context.User.IsInRole("gerente") || Context.User.IsInRole("pizzaiolo") || Context.User.IsInRole("entregador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Pedido" asp-action="Index" asp-link-class="link-ativo">Acompanhar Pedidos </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Pedido" asp-action="Index" asp-link-class="link-ativo">Meus Pedidos </a>
                            </li>
                        }
                        @if (Context.User.IsInRole("administrador") || Context.User.IsInRole("gerente"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Categoria" asp-action="Index" asp-link-class="link-ativo">Categorias </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Produto" asp-action="Index" asp-link-class="link-ativo">Produtos</a>
                            </li>

                            @if (Context.User.IsInRole("administrador"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Estado" asp-action="Index" asp-link-class="link-ativo">Estados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Cidade" asp-action="Index" asp-link-class="link-ativo">Cidades</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Dashboard" asp-action="Index" asp-link-class="link-ativo">Painel de Dados</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Usuario" asp-action="Index" asp-link-class="link-ativo">Usuários</a>
                            </li>
                        }
                    }
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li class="nav-item me-4">
                        <a class="nav-link" asp-controller="ShoppingCart" asp-action="Index" asp-link-class="link-ativo"><i class="bi-cart"></i></a>
                    </li>
                    <partial name="_LoginLogoutLinkPartial" />
                </ul>
            </div>
        </div>
    </nav>

    <main class="container-xxl main-container" role="main">
        @RenderBody()
    </main>

    <!--Div do spinner-->
    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>
    <!------------------>

    <footer class="text-center glass pt-2 border-light-subtle border-top">
        <div class="d-flex flex-column alig-items-center">
            <div>
                <img src="\img\assets\logo01vert.png" width="60" alt="RappiPizzas" />
            </div>
            <div>
                RappiPizzas Delivery WebApp &copy;
                Todos os direitos reservados
            </div>
            @*
            <div>
                <partial name="_NomeCurrentUserRolePartial" />
            </div> *@
        </div>
    </footer>

    <div class="modal fade" tabindex="-1" id="ajaxloginform-modal">
        <div class="modal-dialog">
            <div class="modal-content m-auto" style="border-radius:5px;height:max-content;">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="~/lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="~/lib/bootbox.js/bootbox.min.js"></script>
    <base href="~/" />
    <script src="_framework/blazor.server.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script type="text/javascript" src="~/js/site.js" asp-append-version="true" defer></script>

</body>

</html>

Views/Shared/_LoginLogoutLinkPartial.cshtml
@using PizzaDelivery.Extensions
@inject UserManager<UsuarioModel> _userManager


@if (Context.User.Identity.IsAuthenticated)
{
    var usuario = await _userManager.GetUserAsync(Context.User);
    var roles = await _userManager.GetRolesAsync(usuario);
    var isAdmin = roles.Contains("administrador");
    var usericon = isAdmin ? "bi-person-check" : "bi-person";
    var (FirstName, LastName) = @usuario.NomeCompleto.TplName();

    <li id="UserLink" class="nav-item dropdown" style="border-left: solid 2px #FFD7B3">
        <a class="nav-link dropdown-toggle ms-2 text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="@usericon"></i>
            <b>@FirstName.ToUpper() <span id="spanUserlastname" data-userlastname="@LastName.ToUpper()"></span></b>
        </a>
        <ul class="dropdown-menu dropdown-menu-end login-dropdown">
            <li><a class="dropdown-item" href="/Usuario/AlterarCadastro">Alterar Dados Cadastrais</a></li>
            <li><a class="dropdown-item" asp-controller="Usuario" asp-action="AlterarSenha">Alterar Senha</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" asp-controller="Usuario" asp-action="Logout">Sair</a></li>
        </ul>
    </li>
}
else
{
    <li class="nav-item">
        <a class="link-underline link-underline-opacity-0 ms-0 me-4" asp-action="Cadastrar" asp-controller="Usuario">Cadastre-se</a>
        <a class="btn btn-login" asp-controller="Usuario" asp-action="Login">Entrar</a>
    </li>
}

Views/Shared/_MensagemPartial.cshtml
@if (TempData.ContainsKey("mensagem"))
{
    var mensagem = MensagemViewModel.Desserializar(TempData["mensagem"].ToString());
    @if (mensagem.Tipo == TipoMensagem.Erro)
    {
        <div class="alert alert-warning mt-3 alert-dismissible fade show" role="alert">
            <i class="bi bi-bug"></i>&nbsp; @Html.Raw(mensagem.Texto)
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
    else
    {
        <div class="alert alert-success mt-3 alert-dismissible fade show" role="alert">
            <i class="bi bi-check-circle"></i>&nbsp; @Html.Raw(mensagem.Texto)
            <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        </div>
    }
}

Views/Shared/_NomeCurrentUserRolePartial.cshtml
@using PizzaDelivery.Interfaces;
@using PizzaDelivery.Extensions
@inject UserManager<UsuarioModel> _userManager

@if (Context.User.Identity.IsAuthenticated)
{
    var usuario = await _userManager.GetUserAsync(Context.User);
    var role = (await _userManager.GetRolesAsync(_userManager.FindByNameAsync(usuario.UserName).Result)).FirstOrDefault();

    <span class="badge bg-success bg-gradient text-dark">@role</span>
}